remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: TaoBook
description: collections of books

show_downloads: false
google_analytics: 9776665063
